language: c
dist: focal
install:
  - sudo apt-get update
  - sudo apt-get -y install autoconf-archive ppp libstrophe-dev
compiler:
    - gcc
    - clang
before_script:
    - ./autogen.sh
script:
    - ./configure ${CONFIGURE_OPT}
    - make
    - make check
env:
    - CONFIGURE_OPT="--disable-xmpp"
    - CONFIGURE_OPT="--enable-xmpp"
